---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tox:
    uses: daniel-mizsak/workflows/.github/workflows/tox.yml@main
    with:
      python_versions: "['3.12']"
      codecov: true
    secrets: inherit
