---
name: Falcon Formation Peregrines
on:
  # Run cron job every Monday at 10:00 for goalies and 21:15 for practice,
  # and every Wednesday at 10:00 for goalies and 20:00 for practice.
  schedule:
    - cron: "00 9 * * 1"
    - cron: "15 20 * * 1"
    - cron: "00 9 * * 3"
    - cron: "00 19 * * 3"
  workflow_dispatch:
    inputs:
      goalie:
        type: choice
        description: "Run falcon-formation in goalie mode"
        required: true
        options:
          - 'true'
          - 'false'

jobs:
  falcon-formation-peregrines:
    uses: ./.github/workflows/falcon-formation-template.yml
    if: github.event.schedule == '15 20 * * 1' || github.event.schedule == '00 19 * * 3' || inputs.goalie == 'false'
    secrets:
      team_id: ${{ secrets.FALCONS_1_TEAM_ID }}
      telegram_chat_id: ${{ secrets.FALCONS_1_TELEGRAM_CHAT_ID }}
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}

  falcon-formation-peregrines-goalie:
    uses: ./.github/workflows/falcon-formation-template.yml
    if: github.event.schedule == '00 9 * * 1' || github.event.schedule == '00 9 * * 3' || inputs.goalie == 'true'
    with:
      goalie: true
    secrets:
      team_id: ${{ secrets.FALCONS_1_TEAM_ID }}
      telegram_chat_id: ${{ secrets.FALCONS_1_TELEGRAM_CHAT_ID }}
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
