---
on:
  workflow_call:
    inputs:
      team_name:
        description: "The name of the team."
        type: string
        required: true

    secrets:
      team_id:
        required: true
      activity_name:
        required: true
      telegram_chat_id:
        required: true
      encryption_key:
        required: true

      holdsport_username:
        required: true
      holdsport_password:
        required: true
      telegram_token:

jobs:
  falcon-formation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up python.
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip.
        run: >
          python -m pip install --upgrade pip

      - name: Install package locally.
        run: >
          pip install .

      - name: Decrypt team data.
        run: >
          openssl enc -d -aes-256-cbc
          -in data/${{ inputs.team_name }}.json.enc
          -out data/team.json
          -pass pass:${{ secrets.encryption_key }}
          -pbkdf2

      - name: Run falcon formation.
        env:
          TEAM_NAME: ${{ inputs.team_name }}
          TEAM_ID: ${{ secrets.team_id }}
          HOLDSPORT_USERNAME: ${{ secrets.holdsport_username }}
          HOLDSPORT_PASSWORD: ${{ secrets.holdsport_password }}
        run: |
          {
            echo 'MESSAGE<<EOF'
            falcon-formation ${{ inputs.team_name }}
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Save message as file.
        run: |
            cat <<EOF > falcon-formation.txt
            ${{ env.MESSAGE }}
            EOF

      - name: Save message file as artifact.
        uses: actions/upload-artifact@v4
        with:
          name: falcon-formation
          path: falcon-formation.txt
          retention-days: 5

      - name: Send telegram message.
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.telegram_chat_id }}
          token: ${{ secrets.telegram_token }}
          message: ${{ env.MESSAGE }}
