---
on:
  workflow_call:
    inputs:
      goalie:
        description: "Whether to run falcon-formation in goalie mode."
        type: boolean
        required: false
        default: false

    secrets:
      team_id:
        required: true
      telegram_chat_id:
        required: true
      telegram_token:
        required: true

jobs:
  falcon-formation:
    runs-on: ubuntu-latest
    steps:
      - name: Create teams
        if: ${{ inputs.goalie == false }}
        run: |
          curl --request GET --url https://ff.mlops.top/create_teams?team_id=${{ secrets.team_id }}
          sleep 45
          curl --request GET --url https://ff.mlops.top/get_teams?team_id=${{ secrets.team_id }} --output message.txt

      - name: Get goalie number
        if: ${{ inputs.goalie == true }}
        run: |
          curl --request GET --url https://ff.mlops.top/get_goalie_number?team_id=${{ secrets.team_id }} --output message.txt

      - name: Save teams to environment variable
        run: |
          echo "" >> message.txt
          {
            echo 'MESSAGE<<EOF'
            cat message.txt
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Send message on Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.telegram_chat_id }}
          token: ${{ secrets.telegram_token }}
          message: ${{ env.MESSAGE }}
