---
  name: GHCR
  on:
    push:
      tags:
        - "*"

  jobs:
    ghcr:
      runs-on: ubuntu-latest
      permissions:
        packages: write

      steps:
        - name: Check out the codebase
          uses: actions/checkout@v4

        - name: Login to ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push image
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ghcr.io/daniel-mizsak/falcon-formation:latest
